site_name: Fitness Dashboard User Guide
site_description: A comprehensive guide to understanding and using the Fitness Dashboard for analyzing your workout data, tracking trends, and discovering patterns in your fitness journey.
site_author: Barbara Hidalgo
site_url: https://workouts.barbhs.com

repo_name: dagny099/fitness-dashboard
repo_url: https://github.com/dagny099/fitness-dashboard
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode  
    - scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - content.code.copy
    - content.code.select
    - content.tabs.link

plugins:
  - search:
      lang: en

# Exclude development and archive files from build
exclude_docs: |
  development/
  **/archive/
  **/TODO*
  VISUAL_ASSETS_TOC.md
  assets/diagrams/README.md
  assets/diagrams/architecture-overview.md
  assets/diagrams/data-flow-system.md
  assets/diagrams/developer-workflow.md
  assets/diagrams/ml-pipeline-detailed.md
  assets/diagrams/user-journey-ai-features.md
  assets/diagrams/ai-architecture-flow.md
  assets/diagrams/ml-classification-workflow.md
  assets/diagrams/algorithm-transparency-system.md
  features/
  guides/
  interactive/
  ai/overview.md
  ai/intelligence-dashboard.md
  ai/ml-classification.md
  ai/user-feedback.md
  developer/ai-services.md
  developer/testing.md
  developer/contributing.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quick-start.md
    - Database Setup: getting-started/database-setup.md
    - Your First Insights: getting-started/first-ai-insights.md
  - User Guide:
    - Understanding the Dashboard: user-guide/dashboard-overview.md
    - Quick Reference: user-guide/quick-reference.md
    - Common Tasks: user-guide/user-journeys.md
    - Importing Your Data: user-guide/data-import.md
    - Model Management: user-guide/model-management.md
    - Charts & Visualizations: user-guide/visualizations.md
    - Custom Queries: user-guide/sql-queries.md
  - Advanced:
    - How the Analysis Works: ai/algorithm-transparency.md
    - Technical Architecture: developer/architecture.md
    - API Reference: developer/api-reference.md
  - Reference:
    - Database Schema: reference/database-schema.md
    - Troubleshooting: reference/troubleshooting.md
    - Local Development: deployment/local-development.md
    - Production Setup: deployment/production.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dagny099/fitness-dashboard
    - icon: fontawesome/solid/globe
      link: https://workouts.barbhs.com


copyright: Copyright &copy; 2025 Barbara Hidalgo-Sotelo
